; NSIS Script for Dell LiveCaptions Translator
; Generated by Gemini

!include "MUI2.nsh"

# --- General ---
!define APP_NAME "Dell LiveCaptions Translator"
!define COMPANY_NAME "Dell"
!define APP_VERSION "1.0.0"
!define EXE_NAME "LiveCaptions-Translator.exe"
!define INSTALLER_NAME "DellLiveCaptionsTranslator-Setup.exe"

Name "${APP_NAME}"
OutFile "${INSTALLER_NAME}"
InstallDir "$PROGRAMFILES64\${COMPANY_NAME}\${APP_NAME}"
InstallDirRegKey HKLM "Software\${COMPANY_NAME}\${APP_NAME}" "InstallDir"
RequestExecutionLevel admin

# --- Interface Settings ---
!define MUI_ABORTWARNING
!define MUI_ICON "${PROJECT_ROOT}\src\LiveCaptions-Translator.ico"
!define MUI_UNICON "${PROJECT_ROOT}\src\LiveCaptions-Translator.ico"

# --- Pages ---
!insertmacro MUI_PAGE_WELCOME
!insertmacro MUI_PAGE_COMPONENTS
!insertmacro MUI_PAGE_DIRECTORY
!insertmacro MUI_PAGE_INSTFILES
!insertmacro MUI_PAGE_FINISH

# --- Uninstaller Pages ---
!insertmacro MUI_UNPAGE_CONFIRM
!insertmacro MUI_UNPAGE_INSTFILES

# --- Languages ---
!insertmacro MUI_LANGUAGE "English"

# --- Section Definitions ---
Section "Main Application" SecMain
    SetOutPath $INSTDIR
    
    # Pack the application files - Absolute Path
    File /r "${PROJECT_ROOT}\bin\Release\net8.0-windows\win-x64\publish\*.*"

    # Store installation path in the registry
    WriteRegStr HKLM "Software\${COMPANY_NAME}\${APP_NAME}" "InstallDir" "$INSTDIR"

    # Create uninstaller
    WriteUninstaller "$INSTDIR\uninstall.exe"

    # Create Shortcuts
    CreateDirectory "$SMPROGRAMS\${COMPANY_NAME}"
    CreateShortCut "$SMPROGRAMS\${COMPANY_NAME}\${APP_NAME}.lnk" "$INSTDIR\${EXE_NAME}"
    CreateShortCut "$DESKTOP\${APP_NAME}.lnk" "$INSTDIR\${EXE_NAME}"

    # Write registry keys for Add/Remove Programs
    WriteRegStr HKLM "Software\Microsoft\Windows\CurrentVersion\Uninstall\${APP_NAME}" "DisplayName" "${APP_NAME}"
    WriteRegStr HKLM "Software\Microsoft\Windows\CurrentVersion\Uninstall\${APP_NAME}" "UninstallString" '"$INSTDIR\uninstall.exe"'
    WriteRegStr HKLM "Software\Microsoft\Windows\CurrentVersion\Uninstall\${APP_NAME}" "DisplayIcon" "$INSTDIR\${EXE_NAME}"
    WriteRegStr HKLM "Software\Microsoft\Windows\CurrentVersion\Uninstall\${APP_NAME}" "Publisher" "${COMPANY_NAME}"
    WriteRegStr HKLM "Software\Microsoft\Windows\CurrentVersion\Uninstall\${APP_NAME}" "DisplayVersion" "${APP_VERSION}"
    WriteRegDWORD HKLM "Software\Microsoft\Windows\CurrentVersion\Uninstall\${APP_NAME}" "NoModify" 1
    WriteRegDWORD HKLM "Software\Microsoft\Windows\CurrentVersion\Uninstall\${APP_NAME}" "NoRepair" 1
SectionEnd

Section "Visual C++ Redistributable" SecVCRedist
    SetOutPath "$TEMP"
    File "${PROJECT_ROOT}\scripts\deployment\VC_redist.x64.exe"
    
    DetailPrint "Installing Microsoft Visual C++ 2015-2022 Redistributable (x64)..."
    ExecWait '"$TEMP\VC_redist.x64.exe" /install /passive /norestart'
    
    Delete "$TEMP\VC_redist.x64.exe"
SectionEnd

# --- Uninstaller Section ---
Section "Uninstall"
    # Remove files
    RMDir /r "$INSTDIR"

    # Remove shortcuts
    Delete "$SMPROGRAMS\${COMPANY_NAME}\${APP_NAME}.lnk"
    RMDir "$SMPROGRAMS\${COMPANY_NAME}"
    Delete "$DESKTOP\${APP_NAME}.lnk"

    # Remove registry keys
    DeleteRegKey HKLM "Software\Microsoft\Windows\CurrentVersion\Uninstall\${APP_NAME}"
    DeleteRegKey HKLM "Software\${COMPANY_NAME}\${APP_NAME}"
SectionEnd


# --- Descriptions for components page ---
!insertmacro MUI_FUNCTION_DESCRIPTION_BEGIN
    !insertmacro MUI_DESCRIPTION_TEXT ${SecMain} "The main application files for the Live Captions Translator."
    !insertmacro MUI_DESCRIPTION_TEXT ${SecVCRedist} "Required runtime libraries (Microsoft Visual C++) for the AI engine (Ollama). Will be skipped if already installed."
!insertmacro MUI_FUNCTION_DESCRIPTION_END 